import type { WorldEvent } from "@/lib/orpc-types"

export const MOCK_EVENTS: Omit<WorldEvent, "id" | "userId" | "creatorName" | "agentAddress">[] = [
  // Conflict
  {
    worldIdVerified: false,
    imageUrls: [],
    title: "Ceasefire Negotiations Stall in Eastern Region",
    description: "Peace talks between opposing factions have broken down after disagreements over territorial boundaries.",
    category: "conflict",
    severity: "critical",
    coordinates: [48.3794, 31.1656],
    location: "Eastern Europe",
    timestamp: "2026-04-03T08:30:00Z",
    source: "Reuters",
    agentAddress: null,
    creatorName: "John Doe",
  },
  {
    worldIdVerified: false,
    imageUrls: [],
    title: "Maritime Dispute Escalation in South China Sea",
    description: "Naval vessels from multiple nations converge as territorial claims intensify near contested islands.",
    category: "conflict",
    severity: "high",
    coordinates: [14.5, 114.0],
    location: "South China Sea",
    timestamp: "2026-04-03T06:15:00Z",
    source: "AP News",
    agentAddress: null,
    creatorName: "John Doe",
  },
  {
    worldIdVerified: false,
    imageUrls: [],
    title: "Cross-Border Tensions Rise in Sahel Region",
    description: "Increased military activity reported along multiple borders in West Africa.",
    category: "conflict",
    severity: "medium",
    coordinates: [14.4974, 2.1278],
    location: "Niger-Mali Border",
    timestamp: "2026-04-02T22:00:00Z",
    source: null,
    agentAddress: null,
    creatorName: "John Doe",
  },
  // Natural Disasters
  {
    worldIdVerified: false,
    imageUrls: [],
    title: "7.2 Magnitude Earthquake Hits Central Japan",
    description: "Major earthquake recorded off the coast. Tsunami warnings issued for coastal regions.",
    category: "natural-disaster",
    severity: "critical",
    coordinates: [35.6762, 139.6503],
    location: "Honshu, Japan",
    timestamp: "2026-04-03T04:12:00Z",
    source: "USGS",
    agentAddress: null,
    creatorName: "John Doe",
  },
  {
    worldIdVerified: false,
    imageUrls: [],
    title: "Category 4 Hurricane Approaching Gulf Coast",
    description: "Hurricane Maria strengthens as it approaches the southern United States coastline.",
    category: "natural-disaster",
    severity: "critical",
    coordinates: [26.0, -89.0],
    location: "Gulf of Mexico",
    timestamp: "2026-04-03T10:00:00Z",
    source: "NOAA",
    agentAddress: null,
    creatorName: "John Doe",
  },
  {
    worldIdVerified: false,
    imageUrls: [],
    title: "Severe Flooding in Bangladesh Delta",
    description: "Monsoon rains cause unprecedented flooding displacing thousands of residents.",
    category: "natural-disaster",
    severity: "high",
    coordinates: [23.685, 90.3563],
    location: "Dhaka, Bangladesh",
    timestamp: "2026-04-02T18:30:00Z",
    source: null,
    agentAddress: null,
    creatorName: "John Doe",
  },
  {
    worldIdVerified: false,
    imageUrls: [],
    title: "Wildfire Season Intensifies in Southern Australia",
    description: "Multiple bushfires burning across New South Wales amid record temperatures.",
    category: "natural-disaster",
    severity: "high",
    coordinates: [-33.8688, 151.2093],
    location: "New South Wales, Australia",
    timestamp: "2026-04-03T01:45:00Z",
    source: null,
    agentAddress: null,
    creatorName: "John Doe",
  },
  // Politics
  {
    worldIdVerified: false,
    imageUrls: [],
    title: "EU Summit on Digital Sovereignty",
    description: "European leaders convene in Brussels to discuss AI regulation and tech independence.",
    category: "politics",
    severity: "medium",
    coordinates: [50.8503, 4.3517],
    location: "Brussels, Belgium",
    timestamp: "2026-04-03T09:00:00Z",
    source: "Euronews",
    agentAddress: null,
    creatorName: "John Doe",
  },
  {
    worldIdVerified: false,
    imageUrls: [],
    title: "Snap Elections Called in Brazil",
    description: "Political crisis deepens as president dissolves parliament and calls for early elections.",
    category: "politics",
    severity: "high",
    coordinates: [-15.7975, -47.8919],
    location: "Brasilia, Brazil",
    timestamp: "2026-04-02T20:00:00Z",
    source: null,
    agentAddress: null,
    creatorName: "John Doe",
  },
  {
    worldIdVerified: false,
    imageUrls: [],
    title: "UN Security Council Emergency Session",
    description: "Emergency meeting called to address escalating tensions in multiple regions.",
    category: "politics",
    severity: "high",
    coordinates: [40.749, -73.968],
    location: "New York, USA",
    timestamp: "2026-04-03T14:00:00Z",
    source: "UN News",
    agentAddress: null,
    creatorName: "John Doe",
  },
  {
    worldIdVerified: false,
    imageUrls: [],
    title: "India Passes Landmark Data Privacy Law",
    description: "Parliament approves comprehensive data protection legislation affecting 1.4 billion citizens.",
    category: "politics",
    severity: "medium",
    coordinates: [28.6139, 77.209],
    location: "New Delhi, India",
    timestamp: "2026-04-02T12:30:00Z",
    source: null,
    agentAddress: null,
    creatorName: "John Doe",
  },
  // Economics
  {
    worldIdVerified: false,
    imageUrls: [],
    title: "Global Markets Tumble on Rate Hike Fears",
    description: "Stock markets across Asia and Europe fall sharply on unexpected inflation data.",
    category: "economics",
    severity: "high",
    coordinates: [35.6762, 139.6503],
    location: "Tokyo, Japan",
    timestamp: "2026-04-03T02:00:00Z",
    source: "Bloomberg",
    agentAddress: null,
    creatorName: "John Doe",
  },
  {
    worldIdVerified: false,
    imageUrls: [],
    title: "OPEC+ Announces Production Cuts",
    description: "Oil cartel agrees to reduce output by 2M barrels per day starting next month.",
    category: "economics",
    severity: "high",
    coordinates: [24.4539, 54.3773],
    location: "Abu Dhabi, UAE",
    timestamp: "2026-04-03T11:00:00Z",
    source: null,
    agentAddress: null,
    creatorName: "John Doe",
          },
  {
    worldIdVerified: false,
    imageUrls: [],
    title: "Nigeria Launches Digital Currency Phase 2",
    description: "Central bank expands eNaira program to rural areas with 50M new wallets.",
    category: "economics",
    severity: "medium",
    coordinates: [9.082, 7.4913],
    location: "Abuja, Nigeria",
    timestamp: "2026-04-02T15:00:00Z",
    source: null,
    agentAddress: null,
    creatorName: "John Doe",
  },
  {
    worldIdVerified: false,
    imageUrls: [],
    title: "Silicon Valley Bank Run Fears Resurface",
    description: "Regional bank stocks drop 15% after earnings miss sparks contagion concerns.",
    category: "economics",
    severity: "high",
    coordinates: [37.3861, -122.0839],
    location: "San Francisco, USA",
    timestamp: "2026-04-03T16:30:00Z",
    source: null,
    agentAddress: null,
    creatorName: "John Doe",
  },
  // Health
  {
    worldIdVerified: false,
    imageUrls: [],
    title: "WHO Declares New Pandemic Alert Level",
    description: "Novel respiratory virus identified in Southeast Asia triggers international concern.",
    category: "health",
    severity: "critical",
    coordinates: [13.7563, 100.5018],
    location: "Bangkok, Thailand",
    timestamp: "2026-04-03T07:00:00Z",
    source: "WHO",
    agentAddress: null,
    creatorName: "John Doe",
  },
  {
    worldIdVerified: false,
    imageUrls: [],
    title: "Breakthrough Cancer Treatment Approved",
    description: "FDA greenlights revolutionary mRNA-based therapy showing 90% efficacy in trials.",
    category: "health",
    severity: "low",
    coordinates: [38.9072, -77.0369],
    location: "Washington DC, USA",
    timestamp: "2026-04-02T19:00:00Z",
    source: null,
    agentAddress: null,
    creatorName: "John Doe",
  },
  {
    worldIdVerified: false,
    imageUrls: [],
    title: "Cholera Outbreak in Eastern Congo",
    description: "Rapid spread of waterborne disease affects 50,000+ in displaced persons camps.",
    category: "health",
    severity: "high",
    coordinates: [-1.6741, 29.2339],
    location: "Goma, DRC",
    timestamp: "2026-04-02T10:00:00Z",
    source: null,
    agentAddress: null,
    creatorName: "John Doe",
  },
  // Technology
  {
    worldIdVerified: false,
    imageUrls: [],
    title: "Major Undersea Cable Cut Disrupts Internet",
    description: "Three submarine cables severed simultaneously in the Mediterranean affecting connectivity.",
    category: "technology",
    severity: "high",
    coordinates: [35.0, 18.0],
    location: "Mediterranean Sea",
    timestamp: "2026-04-03T05:30:00Z",
    source: null,
    agentAddress: null,
    creatorName: "John Doe",
  },
  {
    worldIdVerified: false,
    imageUrls: [],
    title: "Massive Ransomware Attack on European Hospitals",
    description: "Coordinated cyberattack takes down hospital systems across Germany and France.",
    category: "technology",
    severity: "critical",
    coordinates: [52.52, 13.405],
    location: "Berlin, Germany",
    timestamp: "2026-04-03T03:15:00Z",
    source: "CyberNews",
    agentAddress: null,
    creatorName: "John Doe",
  },
  {
    worldIdVerified: false,
    imageUrls: [],
                      title: "Starlink Gen3 Achieves Global Coverage",
    description: "SpaceX announces full global broadband coverage including polar regions.",
    category: "technology",
    severity: "low",
    coordinates: [28.5721, -80.648],
    location: "Cape Canaveral, USA",
    timestamp: "2026-04-02T21:00:00Z",
    source: null,
    agentAddress: null,
    creatorName: "John Doe",
  },
  {
    worldIdVerified: false,
    imageUrls: [],
    title: "China Unveils Quantum Computing Breakthrough",
    description: "New quantum processor achieves 1000+ qubit milestone with error correction.",
    category: "technology",
    severity: "medium",
    coordinates: [31.2304, 121.4737],
    location: "Shanghai, China",
    timestamp: "2026-04-03T08:00:00Z",
    source: null,
    agentAddress: null,
    creatorName: "John Doe",
  },
  // Environment
  {
    worldIdVerified: false,
    imageUrls: [],
    title: "Amazon Deforestation Hits Record Monthly Rate",
    description: "Satellite data shows 1,200 sq km cleared in March alone despite pledges.",
    category: "environment",
    severity: "high",
    coordinates: [-3.4653, -62.2159],
    location: "Manaus, Brazil",
    timestamp: "2026-04-03T13:00:00Z",
    source: "INPE",
    agentAddress: null,
    creatorName: "John Doe",
  },
  {
    worldIdVerified: false,
    imageUrls: [],
    title: "Arctic Ice Shelf Collapse Accelerates",
    description: "Largest remaining ice shelf in the Arctic loses 800 sq km in 48 hours.",
    category: "environment",
    severity: "critical",
    coordinates: [82.5, 62.0],
    location: "Arctic Ocean",
    timestamp: "2026-04-02T16:00:00Z",
    source: null,
    agentAddress: null,
    creatorName: "John Doe",
  },
  {
    worldIdVerified: false,
    imageUrls: [],
    title: "Coral Bleaching Event Spreads Across Pacific",
    description: "Fourth global bleaching event confirmed affecting 70% of monitored reefs.",
    category: "environment",
    severity: "high",
    coordinates: [-16.5, 168.0],
    location: "Pacific Ocean",
    timestamp: "2026-04-03T00:30:00Z",
    source: null,
    agentAddress: null,
    creatorName: "John Doe",
      },
  {
    worldIdVerified: false,
    imageUrls: [],
    title: "Record Air Pollution in Delhi NCR",
    description: "AQI exceeds 500 for third consecutive day, schools and offices shut.",
    category: "environment",
    severity: "high",
    coordinates: [28.6139, 77.209],
    location: "Delhi, India",
    timestamp: "2026-04-03T06:00:00Z",
    source: null,
    agentAddress: null,
    creatorName: "John Doe",
  },
  // Social
  {
    worldIdVerified: false,
    imageUrls: [],
    title: "Mass Protests in Nairobi Over Cost of Living",
    description: "Hundreds of thousands take to streets demanding government action on inflation.",
    category: "social",
    severity: "high",
    coordinates: [-1.2921, 36.8219],
    location: "Nairobi, Kenya",
    timestamp: "2026-04-03T09:30:00Z",
    source: null,
    agentAddress: null,
    creatorName: "John Doe",
  },
  {
    worldIdVerified: false,
    imageUrls: [],
    title: "Student Protests Sweep South Korea",
    description: "University students nationwide protest AI-driven hiring practices and job displacement.",
    category: "social",
    severity: "medium",
    coordinates: [37.5665, 126.978],
    location: "Seoul, South Korea",
    timestamp: "2026-04-03T07:45:00Z",
    source: null,
    agentAddress: null,
    creatorName: "John Doe",
  },
  {
    worldIdVerified: false,
    imageUrls: [],
    title: "Global Climate Strike — 10M Participants",
    description: "Largest coordinated climate action in history spans 150 countries simultaneously.",
    category: "social",
    severity: "medium",
    coordinates: [59.3293, 18.0686],
    location: "Stockholm, Sweden",
    timestamp: "2026-04-02T14:00:00Z",
    source: null,
    agentAddress: null,
    creatorName: "John Doe",
  },
  {
    worldIdVerified: false,
    imageUrls: [],
    title: "Water Rationing Sparks Unrest in Mexico City",
    description: "Severe water shortages lead to clashes between residents and authorities.",
    category: "social",
    severity: "high",
    coordinates: [19.4326, -99.1332],
    location: "Mexico City, Mexico",
    timestamp: "2026-04-03T12:00:00Z",
    source: null,
    agentAddress: null,
    creatorName: "John Doe",
  },
  {
    worldIdVerified: false,
    imageUrls: [],
    title: "Historic Peace Agreement Signed in Horn of Africa",
    description: "Decades-long conflict officially ends with multilateral peace treaty.",
    category: "conflict",
    severity: "low",
    coordinates: [9.145, 40.4897],
    location: "Addis Ababa, Ethiopia",
    timestamp: "2026-04-02T17:00:00Z",
    source: "BBC",
    agentAddress: null,
    creatorName: "John Doe",
  },
  {
    worldIdVerified: false,
    imageUrls: [],
        title: "Volcanic Eruption in Iceland",
    description: "Fagradalsfjall erupts again, disrupting air travel across Northern Europe.",
    category: "natural-disaster",
    severity: "medium",
    coordinates: [63.9, -22.27],
    location: "Reykjanes Peninsula, Iceland",
    timestamp: "2026-04-03T11:20:00Z",
    source: null,
    agentAddress: null,
    creatorName: "John Doe",
  },
]
